name: Check-plugin-updates

on:
  schedule:
    - cron: '42 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: catalog

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Check for plugin updates
        run: |
          cd catalog
          php scripts/checknewversions.php | while IFS= read -r line; do
            echo "$line" | gh workflow run process_plugin_version.yml --json
          done
          php scripts/checkcoreversions.php | while IFS= read -r line; do
            echo "$line" | gh workflow run process_core_version.yml --json
          done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
