name: Check-plugin-updates

on:
  workflow_dispatch:
    inputs:
      phpversion:
        description: "PHP version"
        type: string
        default: "8.2"
  # schedule:
  #   - cron: '30 5 * * 1,3'
  #   - cron: '30 5,17 * * 2,4'

jobs:
  check-updates:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: catalog

      - name: Setup PHP ${{ github.event.inputs.phpversion }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ github.event.inputs.phpversion }}
          coverage: none

      - name: Check for plugin updates
        run: |
          cd catalog
          php scripts/checknewversions.php | while IFS= read -r line; do
            echo "$line" | gh workflow run process_plugin_version.yml --json
          done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
