name: Process-plugin-version

on:
  workflow_dispatch:
    inputs:
      plugin:
        description: 'Plugin name'
        type: string
        required: true
      pluginversion:
        description: 'Plugin version'
        type: string
        required: true
      downloadurl:
        description: 'Plugin download URL'
        type: string
        required: true
      moodlebranch:
        description: 'Moodle branch'
        type: string
        required: true
      phpversion:
        description: 'PHP version'
        type: string
        required: true
      database:
        description: 'Database type (mariadb or postgres)'
        type: string
        default: mariadb

jobs:
  process-version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: catalog

      - name: Download specified plugin version
        run: |
          # Download the specified plugin version
          echo "========================================"
          echo "Plugin: ${{ github.event.inputs.plugin }}"
          echo "Version: ${{ github.event.inputs.pluginversion }}"
          echo "Download URL: ${{ github.event.inputs.downloadurl }}"
          echo "Moodle branch: ${{ github.event.inputs.moodlebranch }}"
          echo "PHP version: ${{ github.event.inputs.phpversion }}"
          echo "========================================"
          url="${{ github.event.inputs.downloadurl }}"
          curl -L "$url" -o plugin.zip || exit 1
          unzip -d tmp plugin.zip
          rm plugin.zip
          pluginpath=`ls -d1 tmp/* | head -1`
          mv $pluginpath plugin

      - name: Setup PHP ${{ github.event.inputs.phpversion }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ github.event.inputs.phpversion }}
          #extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          # If you are not using code coverage, keep "none". Otherwise, use "pcov" (Moodle 3.10 and up) or "xdebug".
          # If you try to use code coverage with "none", it will fallback to phpdbg (which has known problems).
          coverage: none

      - name: Detect Moodle branch
        id: detectbranch
        run: |
          BRANCH=`php catalog/scripts/findmoodlebranch.php ./plugin`
          echo "Detected Moodle branch: $BRANCH"
          if [[ "$BRANCH" < "${{ github.event.inputs.branch }}" ]]; then
            BRANCH="${{ github.event.inputs.moodlebranch }}"
          fi
          echo "MOODLE_BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "========================================"
          echo "Moodle branch: $BRANCH"
          echo "========================================"

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          moodle-plugin-ci add-plugin lmscloud-io/moodle-tool_wsdiscovery
          php catalog/scripts/getdependencies.php ./plugin $MOODLE_BRANCH ./moodle-plugin-ci-plugins || exit 1

      - name: Install moodle
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
          pushd moodle
          if [[ "$MOODLE_BRANCH" < "MOODLE_401_STABLE" ]]; then
            php admin/cli/install_database.php --adminuser=admin --adminpass=admin --adminemail=i@am.invalid --agree-license --fullname=T --shortname=T || exit 1
          else
            php admin/cli/install_database.php --adminuser=admin --adminpass=admin --adminemail=i@am.invalid --agree-license --fullname=T --shortname=T --supportemail=i@am.invalid || exit 1
          fi
          popd

        env:
          DB: ${{ github.event.inputs.database }}

      - name: Running wsdiscovery
        run: |
          cd moodle
          [ -d "public" ] && PUBLIC="public/" || PUBLIC=""
          php ${PUBLIC}admin/tool/wsdiscovery/cli/generate_json.php --include=addons --group-by-component > ./temp.json || exit 1
          cd ../catalog
          git config --global user.name 'LMSCloud'
          git config --global user.email 'contrib@lmscloud.io'
          git pull
          php scripts/processjson.php < ../moodle/temp.json
          echo ${{ github.event.inputs.pluginversion }} >> plugins/${{ github.event.inputs.plugin }}/processed.txt
          php scripts/fixlistings.php
          git add .
          git commit -am "Update ${{ github.event.inputs.plugin }}, version ${{ github.event.inputs.pluginversion }}"
          git push
