name: Process-plugin-version-test

on:
  workflow_dispatch:
    inputs:
      plugin:
        description: "Plugin name"
        required: true
        type: string
      pluginversion:
        description: "Plugin version"
        required: true
        type: string

jobs:
  process-version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: catalog

      - name: Test step
        run: |
          echo "---------------------------"
          echo "Plugin-input: ${{ github.event.inputs.plugin }}
          echo "Plugin-event: ${{ github.event.client_payload.plugin }}"
          echo "Plugin version: ${{ github.event.client_payload.pluginversion }}"
          echo "Action: ${{ github.event.action }}"
          echo "---------------------------"
